---
driver:
  name: docker
  sudo: true

provisioner:
  hosts: ubuntu-22.04
  become: true
  name: ansible_playbook
  require_chef_for_busser: false
  require_ruby_for_busser: false
  ansible_verbosity: 2
  ansible_verbose: false
  # starting playbook is at: test/integration/default/default.yml

verifier:
  name: inspec

platforms:
  - name: ubuntu-22.04

suites:
  - name: default
